<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataflowanalysisextension" nsURI="http://www.example.org/dataflowanalysisextension"
    nsPrefix="dataflowanalysisextension">
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedOperationIdentification" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignature" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedParameterIdentification" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedOperation" lowerBound="1"
        eType="#//ProvidedOperationIdentification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedParameterCharacteristicAnnotation"
      eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement #//CharacteristicsAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedParameter" lowerBound="1"
        eType="#//ProvidedParameterIdentification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacteristicsAnnotation" abstract="true"
      eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//EnumCharacteristic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionRoot" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedParameterIdentification"
        lowerBound="1" upperBound="-1" eType="#//ProvidedParameterIdentification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterAnnotations" lowerBound="1"
        upperBound="-1" eType="#//ProvidedParameterCharacteristicAnnotation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
