<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="parameterannotation" nsURI="http://www.example.org/parameterannotation"
    nsPrefix="parameterannotation">
  <eClassifiers xsi:type="ecore:EClass" name="CharacteristicsAnnotation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" upperBound="-1"
        eType="ecore:EClass ../../org.dataflowanalysis.pcm.extension.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//EnumCharacteristic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralOperationParameterIdentification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignature" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedOperationParameterIdentification"
      eSuperTypes="#//GeneralOperationParameterIdentification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationProvidedRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterAnnotation" eSuperTypes="#//CharacteristicsAnnotation ../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterIdentification"
        lowerBound="1" eType="#//GeneralOperationParameterIdentification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterAnnotations" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//ParameterAnnotation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
