package edu.kit.kastel.sdq.coupling.alignment.generation.javacodegenerator.templates

import edu.kit.kastel.sdq.coupling.models.java.members.Method
import edu.kit.kastel.sdq.coupling.models.java.members.Parameter

abstract class MethodGenerationTemplate{
	
	protected Method currentMethod;
	
	def String generate() '''
		«generateAnnotationsAndComments()»
		«generateHeader()»{
			«generateBody()»
		}
	'''
	
	protected def String generateAnnotationsAndComments() ''''''
	
	protected def String generateHeader() '''public «IF currentMethod.returntype !== null»«currentMethod.returntype.name»«ELSE»void«ENDIF» «currentMethod.name» («generateParameters()»)'''
	
	protected def String generateParameters()'''«FOR parameter : currentMethod.parameter SEPARATOR ", "»«generateParameter(parameter)»«ENDFOR»'''
	
	protected def String generateParameter(Parameter parameter)'''
		«generateAnnotations(parameter)» «parameter.type.name» «parameter.name»
	'''
	
	protected def String generateAnnotations(Parameter parameter)''''''
	
	protected def String generateBody() '''//TODO: generated by coupling'''
	
	public def void setCurrentMethod(Method newMethod){
		this.currentMethod = newMethod;
	} 
	
	public def Method getCurrentMethod(){
		return this.currentMethod;
	}
	
	
}
