<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codeqlscar" nsURI="http://www.example.org/codeqlscar" nsPrefix="codeqlscar">
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeAnalysisResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemElementIdentifications"
        upperBound="-1" eType="#//SystemElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityLevels" upperBound="-1"
        eType="#//SecurityLevel_SCAR" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultEntries" upperBound="-1"
        eType="#//Result" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleIds" upperBound="-1"
        eType="#//RuleId" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="#//ResultEntryElement">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" lowerBound="1" containment="true">
      <eGenericType eClassifier="#//ResultEntryElement">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleId" lowerBound="1"
        eType="#//RuleId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultEntryElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//SystemElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemElement" lowerBound="1">
      <eGenericType eTypeParameter="#//ResultEntryElement/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityLevel" lowerBound="1"
        eType="#//SecurityLevel_SCAR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter_SCAR" eSuperTypes="#//SystemElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullyQualifiedClassName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field_SCAR" eSuperTypes="#//SystemElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullyQualifiedClassName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityLevel_SCAR" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//Entity"/>
</ecore:EPackage>
