<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codeql" nsURI="http://www.example.org/codeql" nsPrefix="codeql">
  <eClassifiers xsi:type="ecore:EClass" name="CodeQLRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tainttrackingRoot" lowerBound="1"
        eType="#//tainttracking/TainttrackingRoot" containment="true"/>
  </eClassifiers>
  <eSubpackages name="tainttracking" nsURI="http://www.example.org/codeql/tainttracking"
      nsPrefix="tainttracking">
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterNode" eSuperTypes="#//tainttracking/Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../edu.kit.kastel.sdq.coupling.models.java/model/java.ecore#//members/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SecurityLevel" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="TainttrackingRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#//tainttracking/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
          eType="#//tainttracking/Configuration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliedSecurityLevel"
          upperBound="-1" eType="#//tainttracking/SecurityLevel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="securityLevelAnnotations"
          upperBound="-1" eType="#//tainttracking/SecurityLevelAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allowedFlows" upperBound="-1"
          eType="#//tainttracking/AllowedFlow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SecurityLevelAnnotation" eSuperTypes="../../edu.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="securityLevel" lowerBound="1"
          eType="#//tainttracking/SecurityLevel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterAnnotation" eSuperTypes="#//tainttracking/SecurityLevelAnnotation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../edu.kit.kastel.sdq.coupling.models.java/model/java.ecore#//members/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllowedFlow">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//tainttracking/SecurityLevel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//tainttracking/SecurityLevel"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
