<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="joana" nsURI="http://www.example.org/joana" nsPrefix="joana">
  <eClassifiers xsi:type="ecore:EClass" name="JOANARoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationroot" lowerBound="1"
        upperBound="-1" eType="#//joanasecurity/SpecificationRoot" containment="true"/>
  </eClassifiers>
  <eSubpackages name="joanasecurity" nsURI="http://www.example.org/joana/joanasecurity"
      nsPrefix="joanasecurity">
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="../../org.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement #//joanasecurity/SystemElementIdentifying"/>
    <eClassifiers xsi:type="ecore:EClass" name="EntryPoint" eSuperTypes="../../org.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement #//joanasecurity/MethodIdentifying">
      <eStructuralFeatures xsi:type="ecore:EReference" name="level" upperBound="-1"
          eType="#//joanasecurity/Level" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" upperBound="-1"
          eType="#//joanasecurity/Annotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lattice" lowerBound="1"
          eType="#//joanasecurity/Lattice" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//joanasecurity/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sink" eSuperTypes="#//joanasecurity/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="../../org.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="MayFlow">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//joanasecurity/Level"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//joanasecurity/Level"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Lattice">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayFlow" upperBound="-1"
          eType="#//joanasecurity/MayFlow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemElementIdentifying" abstract="true"
        eSuperTypes="../../org.kit.kastel.sdq.coupling.models.identifier/model/identifier.ecore#//IdentifiedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParametertIdentifying" eSuperTypes="#//joanasecurity/SystemElementIdentifying"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodIdentifying" eSuperTypes="#//joanasecurity/SystemElementIdentifying"/>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificationRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entrypoint" lowerBound="1"
          upperBound="-1" eType="#//joanasecurity/EntryPoint" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="joanasystem" nsURI="http://www.example.org/joana/joanasystem"
      nsPrefix="joanasystem"/>
</ecore:EPackage>
